# Site settings
title: Televisión, internet y filosofía 
author: 
name: Julio Iván Salazar 
email: ji.ss00g@gmail.com
description: "Este sitio web está principalmente dedicado a la divulgación de la filosofía, a través de programas de televisión e internet seleccionados para mostrar la relación de la filosofía con otras áreas, particularmente la ciencia y la tecnología. En él encontrarás código de acceso libre (XML-TEI) para marcar contenido de tipo broadcasting, efocado pero no limitado a la filosofía."
